"""Shared-memory layout constants; must match ZeroAD.Sim.RL.ShmLayout."""

MAGIC = 0x5A414452
VERSION = 2

CMD_IDLE = 0
CMD_RESET = 1
CMD_STEP = 2
CMD_QUIT = 3

HEADER_BYTES = 64
OFF_MAGIC = 0
OFF_VERSION = 4
OFF_SLOTS = 8
OFF_CMD = 12
OFF_SEQ_IN = 16
OFF_SEQ_OUT = 20
OFF_PRIVILEGED = 24
OFF_SEED = 28

MAX_ENTITIES = 512
ENTITY_FEAT = 13
SPATIAL_SIZE = 64
SPATIAL_CHANNELS = 5
SCALAR_COUNT = 11
MAX_SELECTED = 8
N_FUNCTIONS = 32

ENTITIES_BYTES = MAX_ENTITIES * ENTITY_FEAT * 4
SPATIAL_BYTES = SPATIAL_CHANNELS * SPATIAL_SIZE * SPATIAL_SIZE * 4
SCALARS_BYTES = SCALAR_COUNT * 4
MASK_BYTES = 32
ENTITY_MASK_BYTES = MAX_ENTITIES * 4
ACTION_BLOCK_BYTES = 64
ACTION_BYTES = ACTION_BLOCK_BYTES * 2

OFF_TURN = 0
OFF_REWARD = 4
OFF_DONE = 8
OFF_ENTITIES = 16
OFF_SPATIAL = OFF_ENTITIES + ENTITIES_BYTES
OFF_SCALARS = OFF_SPATIAL + SPATIAL_BYTES
OFF_MASK = OFF_SCALARS + SCALARS_BYTES
OFF_ENTITY_MASK = OFF_MASK + MASK_BYTES
OFF_ACTION = OFF_ENTITY_MASK + ENTITY_MASK_BYTES
SLOT_BYTES = OFF_ACTION + ACTION_BYTES

ACT_FUNCTION = 0
ACT_TARGET = 4
ACT_CELL_X = 8
ACT_CELL_Z = 12
ACT_CATALOG = 16
ACT_SELECTED0 = 20
ACT_OPP_BASE = ACTION_BLOCK_BYTES


def file_bytes(slots: int) -> int:
    """Total mmap file size for ``slots`` environments."""
    return HEADER_BYTES + max(1, slots) * SLOT_BYTES


def slot_offset(slot: int) -> int:
    """Byte offset of ``slot`` from the start of the file."""
    return HEADER_BYTES + slot * SLOT_BYTES
