# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: zeroad_rl.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'zeroad_rl.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fzeroad_rl.proto\x12\tzeroad.rl\"\xaa\x01\n\x0bObservation\x12\x10\n\x08\x65ntities\x18\x01 \x03(\x05\x12\x0f\n\x07spatial\x18\x02 \x03(\x05\x12\x0f\n\x07scalars\x18\x03 \x03(\x05\x12\x15\n\rfunction_mask\x18\x04 \x01(\x0c\x12\x0c\n\x04turn\x18\x05 \x01(\r\x12\x0e\n\x06reward\x18\x06 \x01(\x05\x12\x0c\n\x04\x64one\x18\x07 \x01(\x08\x12\x13\n\x0b\x65ntity_mask\x18\x08 \x03(\r\x12\x0f\n\x07\x63\x61talog\x18\t \x03(\x05\"\xc8\x01\n\x06\x41\x63tion\x12\x10\n\x08\x66unction\x18\x01 \x01(\x05\x12\x16\n\x0eselected_index\x18\x02 \x01(\x05\x12\x1b\n\x13target_entity_index\x18\x03 \x01(\x05\x12\x15\n\rtarget_cell_x\x18\x04 \x01(\x05\x12\x15\n\rtarget_cell_z\x18\x05 \x01(\x05\x12\x12\n\ncatalog_id\x18\x06 \x01(\x05\x12\x10\n\x08selected\x18\x07 \x03(\x05\x12#\n\x08opponent\x18\x08 \x01(\x0b\x32\x11.zeroad.rl.Action\"Y\n\x0cResetRequest\x12\x0c\n\x04seed\x18\x01 \x01(\r\x12\x12\n\nprivileged\x18\x02 \x01(\x08\x12\x10\n\x08step_mul\x18\x03 \x01(\x05\x12\x15\n\rcommand_delay\x18\x04 \x01(\x05\"g\n\rClientMessage\x12(\n\x05reset\x18\x01 \x01(\x0b\x32\x17.zeroad.rl.ResetRequestH\x00\x12!\n\x04step\x18\x02 \x01(\x0b\x32\x11.zeroad.rl.ActionH\x00\x42\t\n\x07payload2\xb8\x01\n\x08ZeroAdRl\x12\x38\n\x05Reset\x12\x17.zeroad.rl.ResetRequest\x1a\x16.zeroad.rl.Observation\x12\x31\n\x04Step\x12\x11.zeroad.rl.Action\x1a\x16.zeroad.rl.Observation\x12?\n\x07Session\x12\x18.zeroad.rl.ClientMessage\x1a\x16.zeroad.rl.Observation(\x01\x30\x01\x42\x16\xaa\x02\x13ZeroAD.RlHost.Protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'zeroad_rl_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\023ZeroAD.RlHost.Proto'
  _globals['_OBSERVATION']._serialized_start=31
  _globals['_OBSERVATION']._serialized_end=201
  _globals['_ACTION']._serialized_start=204
  _globals['_ACTION']._serialized_end=404
  _globals['_RESETREQUEST']._serialized_start=406
  _globals['_RESETREQUEST']._serialized_end=495
  _globals['_CLIENTMESSAGE']._serialized_start=497
  _globals['_CLIENTMESSAGE']._serialized_end=600
  _globals['_ZEROADRL']._serialized_start=603
  _globals['_ZEROADRL']._serialized_end=787
# @@protoc_insertion_point(module_scope)
