# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from zeroad_env import zeroad_rl_pb2 as zeroad__rl__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in zeroad_rl_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ZeroAdRlStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Reset = channel.unary_unary(
                '/zeroad.rl.ZeroAdRl/Reset',
                request_serializer=zeroad__rl__pb2.ResetRequest.SerializeToString,
                response_deserializer=zeroad__rl__pb2.Observation.FromString,
                _registered_method=True)
        self.Step = channel.unary_unary(
                '/zeroad.rl.ZeroAdRl/Step',
                request_serializer=zeroad__rl__pb2.Action.SerializeToString,
                response_deserializer=zeroad__rl__pb2.Observation.FromString,
                _registered_method=True)
        self.Session = channel.stream_stream(
                '/zeroad.rl.ZeroAdRl/Session',
                request_serializer=zeroad__rl__pb2.ClientMessage.SerializeToString,
                response_deserializer=zeroad__rl__pb2.Observation.FromString,
                _registered_method=True)


class ZeroAdRlServicer:
    """Missing associated documentation comment in .proto file."""

    def Reset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Step(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Session(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ZeroAdRlServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Reset': grpc.unary_unary_rpc_method_handler(
                    servicer.Reset,
                    request_deserializer=zeroad__rl__pb2.ResetRequest.FromString,
                    response_serializer=zeroad__rl__pb2.Observation.SerializeToString,
            ),
            'Step': grpc.unary_unary_rpc_method_handler(
                    servicer.Step,
                    request_deserializer=zeroad__rl__pb2.Action.FromString,
                    response_serializer=zeroad__rl__pb2.Observation.SerializeToString,
            ),
            'Session': grpc.stream_stream_rpc_method_handler(
                    servicer.Session,
                    request_deserializer=zeroad__rl__pb2.ClientMessage.FromString,
                    response_serializer=zeroad__rl__pb2.Observation.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'zeroad.rl.ZeroAdRl', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('zeroad.rl.ZeroAdRl', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ZeroAdRl:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Reset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/zeroad.rl.ZeroAdRl/Reset',
            zeroad__rl__pb2.ResetRequest.SerializeToString,
            zeroad__rl__pb2.Observation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Step(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/zeroad.rl.ZeroAdRl/Step',
            zeroad__rl__pb2.Action.SerializeToString,
            zeroad__rl__pb2.Observation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Session(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/zeroad.rl.ZeroAdRl/Session',
            zeroad__rl__pb2.ClientMessage.SerializeToString,
            zeroad__rl__pb2.Observation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
