<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <RootNamespace>ZeroAD.RlHost</RootNamespace>
    <AssemblyName>ZeroAD.RlHost</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../ZeroAD.Sim/ZeroAD.Sim.csproj" />
  </ItemGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Grpc.AspNetCore" Version="2.67.0" />
  </ItemGroup>
  <ItemGroup>
    <Protobuf Include="Protos\zeroad_rl.proto" GrpcServices="Server" />
  </ItemGroup>
</Project>
